### ISSUE TITLE
section值跟气泡值不一致

### ISSUE THREAD

**Issue by hwh97** [LiuC520/flutter_seekbar#1]
刻度值
![2018-12-19 4 42 43](https://user-images.githubusercontent.com/23030636/50208931-73e31c00-03ad-11e9-83da-a24e42c09c5e.png)
气泡值
![2018-12-19 4 57 49](https://user-images.githubusercontent.com/23030636/50209681-4c8d4e80-03af-11e9-93db-6a6c4138caaf.png)

这样会导致不一致的吧?(toStringAsFixed带四舍五入的)

**Comment by LiuC520** [comment]
是的，上面的刻度值好像不是我的代码，后面加了个东西
